### ISSUE TITLE
Error at module.js

### ISSUE THREAD

**Issue by GO1984** [DustinJSilk/gekkoga-plus-ui#2]
I want to try your UI, because i like the layout.

while i try to start it up i get following error:

> XX@XXX:~/gekko/gekkoga-plus-ui$ node server -c config/StochRSI.js
module.js:540
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/XXX/gekko/gekkoga-plus-ui/server.js:1:79)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by DustinJSilk** [comment]
im not providing support for this since i started writing [this](https://github.com/DustinJSilk/reactive-trader).

However that error means express isnt installed from where ever you're running the command. Try running `npm install`. Or try `npm install express --save`.

Best of luck
